#!/usr/bin/env python2

'''
See emcc.py. This script forwards to there, noting that we want C++ and not C by default
'''

import os, subprocess, sys
from tools import shared

os.environ['EMMAKEN_CXX'] = '1'
if not os.path.exists(shared.PYTHON):
  print >> sys.stderr, 'warning: PYTHON does not seem to be defined properly in ~/.emscripten (%s)' % shared.PYTHON
exit(subprocess.call([shared.PYTHON, shared.EMCC] + sys.argv[1:]))

