#!/usr/bin/env python

'''
See emcc.py. This script forwards to there, noting that we want C++ and not C by default
'''

import os, subprocess, sys

python = sys.executable if sys.version_info.major == 2 else 'python2'

exit(subprocess.call([python, os.path.join(os.path.dirname(__file__), 'emcc.py')] + sys.argv[1:] + ['--emscripten-cxx']))

