#!/usr/bin/env python2

'''
emar - ar helper script
=======================

This script acts as a frontend replacement for ar. See emcc.
'''

import os, subprocess, sys
from tools import shared

DEBUG = os.environ.get('EMCC_DEBUG')
if DEBUG == "0":
   DEBUG = None

newargs = [shared.LLVM_AR]

skip = False
for arg in sys.argv[1:]:
  if not skip and arg != '--em-config':
    newargs += [arg]
  elif arg == '--em-config':
    skip = True
  elif skip:
    skip = False

if DEBUG:
  print >> sys.stderr, 'emar:', sys.argv, '  ==>  ', newargs

if len(newargs) > 2:
  subprocess.call(newargs)

