#!/usr/bin/env python

'''
emar - ar helper script
=======================

This script acts as a frontend replacement for ar. See emcc.
'''

import os, sys
from tools import shared

DEBUG = os.environ.get('EMCC_DEBUG')

newargs = [shared.LLVM_AR] + sys.argv[1:]

if DEBUG:
  print >> sys.stderr, 'emar:', sys.argv, '  ==>  ', newargs

if len(newargs) > 2:
  os.execvp(shared.LLVM_AR, newargs)

