#!/usr/bin/env python

# This script should work in python 2 *or* 3. It loads emcc.py, which needs python 2.

from tools.toolchain_profiler import ToolchainProfiler
from tools import force_python_version

import sys

if __name__ == '__main__' and not force_python_version.run(__file__):
  ToolchainProfiler.record_process_start()
  import emcc
  emcc.run()
  sys.exit(0)
