#!/usr/bin/env python2

import os, subprocess, sys
from tools import shared

configure_path = shared.path_from_root('emconfigure')
exit(subprocess.call([shared.PYTHON, configure_path] + sys.argv[1:]))

