#!/usr/bin/env python2

'''
This is a helper script. It runs ./configure for you, setting
the environment variables to use emcc and so forth. Usage:

  emconfigure ./configure [FLAGS]

You can also use this for cmake and other configure-like
stages. What happens is that all compilations done during
this command are to native code, not JS, so that configure
tests will work properly.

Relevant defines:

  CONFIGURE_CC - see emcc
'''

import os, sys
from tools import shared

shared.Building.configure(sys.argv[1:])

