#!/usr/bin/env python

# This script should work in python 2 *or* 3. It loads emmake.py, which needs python 2.

from tools.toolchain_profiler import ToolchainProfiler

import sys



if __name__ == '__main__':
  ToolchainProfiler.record_process_start()
  import emmake
  emmake.run()
  sys.exit(0)
