#!/usr/bin/env python

# This script should work in python 2 *or* 3. It loads emrun.py, which needs python 2.

import sys

if sys.version_info.major == 2:
  if __name__ == '__main__':
    import emrun
    sys.exit(emrun.main())
else:
  import os, subprocess
  if __name__ == '__main__':
    sys.exit(subprocess.call(['python2', os.path.join(os.path.dirname(__file__), 'emrun.py')] + sys.argv[1:]))
