git grep -I --name-only -z -e '' -- .       \
':!third_party'                             \
':!tests/third_party'                       \
':!tests/glbook'                            \
':!tests/bzip2_test.c'                      \
':!tests/freetype'                          \
':!tests/full_es2_sdlproc.c'                \
':!tests/fuzz'                              \
':!tests/gl_vertex*'                        \
':!tests/optimizer/*.js'                    \
':!tests/openjpeg/syntensity_lobby_s.raw'   \
':!tests/*.out'                             \
':!tests/sockets/ws'                        \
':!tests/benchmark/linpack2.c'              \
':!tests/benchmark/test_lzma_benchmark.c'   \
':!tests/hello_world_gles_deriv.c'          \
':!tests/http.h'                            \
':!tests/life.c'                            \
':!tests/perspective.c'                     \
':!tests/raytrace.cpp'                      \
':!tests/raytrace.cpp'                      \
':!cmake/Modules/FindOpenAL.cmake'          \
':!docs/emscripten_powered_by_logo.svg'     \
':!docs/paper.tex'                          \
':!media/powered_by_logo.svg'               \
':!media/switch_logo.svg'                   \
':!site/source/_themes'                     \
':!system/include/GL'                       \
':!system/include/GLFW'                     \
':!system/include/SDL'                      \
':!system/include/X11'                      \
':!system/include/libc'                     \
':!system/lib/libc/musl'                    \
':!system/lib/libcxxabi'                    \
':!system/lib/libunwind'                    \
':!system/include/wasi'                     \
':!system/lib/dlmalloc.c'                   \
':!src/promise_polyfill.js'                 \
 | xargs -0 sed -i 's/[ \t]\+\(\r\?\)$/\1/'
