#!/usr/bin/env python3
# Copyright 2026 The Emscripten Authors.  All rights reserved.
# Emscripten is available under two separate licenses, the MIT license and the
# University of Illinois/NCSA Open Source License.  Both these licenses can be
# found in the LICENSE file.

"""Generate C++ header tools/emcc_native/generated_settings.h from Python flag definitions."""

import os
import sys

script_dir = os.path.dirname(os.path.abspath(__file__))
root_dir = os.path.dirname(os.path.dirname(script_dir))
sys.path.insert(0, root_dir)

from emcc import LINK_ONLY_FLAGS
from tools import diagnostics, shared  # noqa: F401
from tools.settings import COMPILE_TIME_SETTINGS
from tools.utils import path_from_root, read_file, write_file

HEADER_PATH = path_from_root('tools/emcc_native/generated_settings.h')


def generate(check_only=False):
  link_flags = sorted(LINK_ONLY_FLAGS)
  compile_settings = sorted(COMPILE_TIME_SETTINGS)
  ems_warnings = sorted(name for name, info in diagnostics.manager.warnings.items() if not info['shared'])

  lines = [
      '/*',
      ' * Copyright 2026 The Emscripten Authors.  All rights reserved.',
      ' * Emscripten is available under two separate licenses, the MIT license and the',
      ' * University of Illinois/NCSA Open Source License.  Both these licenses can be',
      ' * found in the LICENSE file.',
      ' *',
      ' * Auto-generated by tools/emcc_native/gen_settings.py. DO NOT EDIT.',
      ' */',
      '',
      '#ifndef EMCC_NATIVE_GENERATED_SETTINGS_H',
      '#define EMCC_NATIVE_GENERATED_SETTINGS_H',
      '',
      '#include <string>',
      '#include <unordered_set>',
      '',
      'namespace emscripten {',
      '',
      'inline const std::unordered_set<std::string> LINK_ONLY_FLAGS = {',
  ]

  for flag in link_flags:
    lines.append(f'  "{flag}",')
  lines.extend([
      '};',
      '',
      'inline const std::unordered_set<std::string> COMPILE_TIME_SETTINGS = {',
  ])

  for setting in compile_settings:
    lines.append(f'  "{setting}",')
  lines.extend([
      '};',
      '',
      'inline const std::unordered_set<std::string> EMSCRIPTEN_ONLY_WARNINGS = {',
  ])

  for warning in ems_warnings:
    lines.append(f'  "{warning}",')
  lines.extend([
      '};',
      '',
      '} // namespace emscripten',
      '',
      '#endif // EMCC_NATIVE_GENERATED_SETTINGS_H',
  ])

  content = '\n'.join(lines) + '\n'

  if check_only:
    existing = read_file(HEADER_PATH)
    if existing != content:
      print(f'Error: {HEADER_PATH} is out of date.', file=sys.stderr)
      print('Run tools/emcc_native/gen_settings.py to update it.', file=sys.stderr)
      sys.exit(1)
    print(f'{HEADER_PATH} is up to date.')
  else:
    write_file(HEADER_PATH, content)
    print(f'Wrote {HEADER_PATH}')


if __name__ == '__main__':
  check = '--check' in sys.argv
  generate(check_only=check)
