#ifndef __JAVA_LANG_REFLECT_GENERICDECLARATION__
#define __JAVA_LANG_REFLECT_GENERICDECLARATION__

#include "xmlvm.h"

// Preprocessor constants for interfaces:
#define XMLVM_ITABLE_IDX_java_lang_reflect_GenericDeclaration_getTypeParameters__ 4
// Implemented interfaces:
// Super Class:
#include "java_lang_Object.h"

// Circular references:

XMLVM_DEFINE_CLASS(java_lang_reflect_GenericDeclaration, 0, 0)

extern JAVA_OBJECT __CLASS_java_lang_reflect_GenericDeclaration;
extern JAVA_OBJECT __CLASS_java_lang_reflect_GenericDeclaration_1ARRAY;
extern JAVA_OBJECT __CLASS_java_lang_reflect_GenericDeclaration_2ARRAY;
extern JAVA_OBJECT __CLASS_java_lang_reflect_GenericDeclaration_3ARRAY;
#ifndef XMLVM_FORWARD_DECL_java_lang_reflect_GenericDeclaration
#define XMLVM_FORWARD_DECL_java_lang_reflect_GenericDeclaration
typedef struct java_lang_reflect_GenericDeclaration java_lang_reflect_GenericDeclaration;
#endif

void __INIT_java_lang_reflect_GenericDeclaration();
void __INIT_IMPL_java_lang_reflect_GenericDeclaration();

#endif
