name: 'Install Basic Packages'
description: 'Installs packages missing from GHA runner base'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y xz-utils ninja-build cmake wget
      shell: bash


