/**
 * @type {Object.<string,*>}
 */
var ws = {};

/**
 * @param {string} event
 * @param {function()} callback
 */
ws.on = function(event, callback) {};

/**
 * @param {Object} data
 * @param {Object} flags
 * @param {function()=} callback
 */
ws.send = function(data, flags, callback) {};

/**
* @type {boolean}
*/
ws.binaryType;

/**
 * @type {Object.<string,*>}
 */
var wss = ws.Server;

/**
 * @param {string} event
 * @param {function()} callback
 */
wss.on = function(event, callback) {};

/**
 * @param {function()} callback
 */
wss.broadcast = function(callback) {};

/**
* @type {Object.<string,*>}
*/
wss._socket;

/**
* @type {string}
*/
wss.url;

/**
* @type {string}
*/
wss._socket.remoteAddress;

/**
* @type {number}
*/
wss._socket.remotePort;

/**
 * @suppress {duplicate}
 */
var process;

/**
 * @suppress {duplicate}
 */
var assert;

/**
 * @suppress {duplicate}
 */
var fs;

/**
 * @param {...*} var_args
 * @constructor
 * @nosideeffects
 */
var Buffer = function(var_args) {};

/**
 * @param {ArrayBuffer|SharedArrayBuffer} arrayBuffer
 * @param {number=} byteOffset
 * @param {number=} length
 * @return {nodeBuffer.Buffer}
 * @nosideeffects
 */
Buffer.from = function(arrayBuffer, byteOffset, length) {};

/**
 * nodefs may use the error codes fullname at runtime, so we need to preserve them
 * @see https://github.com/emscripten-core/emscripten/issues/14705
 * @suppress {duplicate}
 * @enum {number}
 */
var ERRNO_CODES;
ERRNO_CODES.EPERM;
ERRNO_CODES.ENOENT;
ERRNO_CODES.ESRCH;
ERRNO_CODES.EINTR;
ERRNO_CODES.EIO;
ERRNO_CODES.ENXIO;
ERRNO_CODES.E2BIG;
ERRNO_CODES.ENOEXEC;
ERRNO_CODES.EBADF;
ERRNO_CODES.ECHILD;
ERRNO_CODES.EAGAIN;
ERRNO_CODES.EWOULDBLOCK;
ERRNO_CODES.ENOMEM;
ERRNO_CODES.EACCES;
ERRNO_CODES.EFAULT;
ERRNO_CODES.ENOTBLK;
ERRNO_CODES.EBUSY;
ERRNO_CODES.EEXIST;
ERRNO_CODES.EXDEV;
ERRNO_CODES.ENODEV;
ERRNO_CODES.ENOTDIR;
ERRNO_CODES.EISDIR;
ERRNO_CODES.EINVAL;
ERRNO_CODES.ENFILE;
ERRNO_CODES.EMFILE;
ERRNO_CODES.ENOTTY;
ERRNO_CODES.ETXTBSY;
ERRNO_CODES.EFBIG;
ERRNO_CODES.ENOSPC;
ERRNO_CODES.ESPIPE;
ERRNO_CODES.EROFS;
ERRNO_CODES.EMLINK;
ERRNO_CODES.EPIPE;
ERRNO_CODES.EDOM;
ERRNO_CODES.ERANGE;
ERRNO_CODES.ENOMSG;
ERRNO_CODES.EIDRM;
ERRNO_CODES.ECHRNG;
ERRNO_CODES.EL2NSYNC;
ERRNO_CODES.EL3HLT;
ERRNO_CODES.EL3RST;
ERRNO_CODES.ELNRNG;
ERRNO_CODES.EUNATCH;
ERRNO_CODES.ENOCSI;
ERRNO_CODES.EL2HLT;
ERRNO_CODES.EDEADLK;
ERRNO_CODES.ENOLCK;
ERRNO_CODES.EBADE;
ERRNO_CODES.EBADR;
ERRNO_CODES.EXFULL;
ERRNO_CODES.ENOANO;
ERRNO_CODES.EBADRQC;
ERRNO_CODES.EBADSLT;
ERRNO_CODES.EDEADLOCK;
ERRNO_CODES.EBFONT;
ERRNO_CODES.ENOSTR;
ERRNO_CODES.ENODATA;
ERRNO_CODES.ETIME;
ERRNO_CODES.ENOSR;
ERRNO_CODES.ENONET;
ERRNO_CODES.ENOPKG;
ERRNO_CODES.EREMOTE;
ERRNO_CODES.ENOLINK;
ERRNO_CODES.EADV;
ERRNO_CODES.ESRMNT;
ERRNO_CODES.ECOMM;
ERRNO_CODES.EPROTO;
ERRNO_CODES.EMULTIHOP;
ERRNO_CODES.EDOTDOT;
ERRNO_CODES.EBADMSG;
ERRNO_CODES.ENOTUNIQ;
ERRNO_CODES.EBADFD;
ERRNO_CODES.EREMCHG;
ERRNO_CODES.ELIBACC;
ERRNO_CODES.ELIBBAD;
ERRNO_CODES.ELIBSCN;
ERRNO_CODES.ELIBMAX;
ERRNO_CODES.ELIBEXEC;
ERRNO_CODES.ENOSYS;
ERRNO_CODES.ENOTEMPTY;
ERRNO_CODES.ENAMETOOLONG;
ERRNO_CODES.ELOOP;
ERRNO_CODES.EOPNOTSUPP;
ERRNO_CODES.EPFNOSUPPORT;
ERRNO_CODES.ECONNRESET;
ERRNO_CODES.ENOBUFS;
ERRNO_CODES.EAFNOSUPPORT;
ERRNO_CODES.EPROTOTYPE;
ERRNO_CODES.ENOTSOCK;
ERRNO_CODES.ENOPROTOOPT;
ERRNO_CODES.ESHUTDOWN;
ERRNO_CODES.ECONNREFUSED;
ERRNO_CODES.EADDRINUSE;
ERRNO_CODES.ECONNABORTED;
ERRNO_CODES.ENETUNREACH;
ERRNO_CODES.ENETDOWN;
ERRNO_CODES.ETIMEDOUT;
ERRNO_CODES.EHOSTDOWN;
ERRNO_CODES.EHOSTUNREACH;
ERRNO_CODES.EINPROGRESS;
ERRNO_CODES.EALREADY;
ERRNO_CODES.EDESTADDRREQ;
ERRNO_CODES.EMSGSIZE;
ERRNO_CODES.EPROTONOSUPPORT;
ERRNO_CODES.ESOCKTNOSUPPORT;
ERRNO_CODES.EADDRNOTAVAIL;
ERRNO_CODES.ENETRESET;
ERRNO_CODES.EISCONN;
ERRNO_CODES.ENOTCONN;
ERRNO_CODES.ETOOMANYREFS;
ERRNO_CODES.EUSERS;
ERRNO_CODES.EDQUOT;
ERRNO_CODES.ESTALE;
ERRNO_CODES.ENOTSUP;
ERRNO_CODES.ENOMEDIUM;
ERRNO_CODES.EILSEQ;
ERRNO_CODES.EOVERFLOW;
ERRNO_CODES.ECANCELED;
ERRNO_CODES.ENOTRECOVERABLE;
ERRNO_CODES.EOWNERDEAD;
ERRNO_CODES.ESTRPIPE;
