SAFE_HEAP_STORE(HEAP8, x, 1);

SAFE_HEAP_STORE(HEAP16, x, 2);

SAFE_HEAP_STORE(HEAP32, x, 3);

SAFE_HEAP_STORE(HEAPU8, x, 4);

SAFE_HEAP_STORE(HEAPU16, x, 5);

SAFE_HEAP_STORE(HEAPU32, x, 6);

SAFE_HEAP_STORE(HEAPF32, x, 7);

SAFE_HEAP_STORE(HEAPF64, x, 8);

SAFE_HEAP_STORE(HEAP64, x, 9n);

SAFE_HEAP_STORE(HEAPU64, x, 10n);

a1 = SAFE_HEAP_LOAD(HEAP8, x);

a2 = SAFE_HEAP_LOAD(HEAP16, x);

a3 = SAFE_HEAP_LOAD(HEAP32, x);

a4 = SAFE_HEAP_LOAD(HEAPU8, x);

a5 = SAFE_HEAP_LOAD(HEAPU16, x);

a6 = SAFE_HEAP_LOAD(HEAPU32, x);

a7 = SAFE_HEAP_LOAD(HEAPF32, x);

a8 = SAFE_HEAP_LOAD(HEAPF64, x);

a9 = SAFE_HEAP_LOAD(HEAP64, x);

a10 = SAFE_HEAP_LOAD(HEAPU64, x);

foo = SAFE_HEAP_STORE(HEAPU8, 1337, 42);

SAFE_HEAP_LOAD(HEAP16, bar(SAFE_HEAP_LOAD(HEAPF64, 5)));

SAFE_HEAP_STORE(HEAPF32, x, SAFE_HEAP_LOAD(HEAP32, y));

function SAFE_HEAP_FOO(ptr) {
  return HEAP8[ptr];
}

function somethingElse() {
  return SAFE_HEAP_LOAD(HEAP8, ptr);
}

HEAP8.length;

SAFE_HEAP_LOAD(HEAP8, length);
