:: Entry point for running python scripts on windows systems.
::
:: Automatically generated by `create_entry_points.py`; DO NOT EDIT.
::
:: To make modifications to this file, edit `tools/run_python_compiler.bat` and
:: then run `tools/create_entry_points.py`

@set EM_PY=%EMSDK_PYTHON%
@if "%EM_PY%"=="" (
  set EM_PY=python
)

@if "%_EMCC_CCACHE%"=="" (
  :: Do regular invocation of the python compiler driver
  set CMD="%EM_PY%" "%~dp0\%~n0.py"
) else (
  :: Remove the ccache env. var, invoke ccache and re-enter this script to take the above branch.
  set _EMCC_CCACHE=
  set CMD=ccache "%~dp0\%~n0.bat"
)

@%CMD% %*
