# Tag release and update changelog
name: Tag release and update Changelog

on:
  workflow_dispatch:
    inputs:
      release-sha:
        required: true
        type: string
permissions:
  contents: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          token: ${{ secrets.EMSCRIPTEN_BOT_TOKEN }}
          fetch-depth: 0
      - name: Create Release
        run: python3 tools/maint/create_release.py --release-commit ${{ inputs.release-sha }}
        env:
          GH_TOKEN: ${{ secrets.EMSCRIPTEN_BOT_TOKEN }}
          GIT_AUTHOR_NAME: emscripten-bot
          GIT_AUTHOR_EMAIL: emscripten-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: emscripten-bot
          GIT_COMMITTER_EMAIL: emscripten-bot@users.noreply.github.com
