
// Part 1

[Constructor(long val)] 
interface Parent {
  long getVal();
  void mulVal(long mul);
};

[Constructor(optional long val)]
interface Child1 {
  long getValSqr(optional long more);
  long getValTimes(optional long times=1);
};

Child1 implements Parent;

[Constructor]
interface Child2 {
  long getValCube();
  static void printStatic();
  void virtualFunc();
  void virtualFunc2();
  void virtualFunc3(long x);
  void virtualFunc4(long x);
  static void runVirtualFunc(Child2 self);
};

Child2 implements Parent;

// TODO: document
[Constructor, JSImplementation="Child2"]
interface Child2JS {
  void virtualFunc();
  void virtualFunc2();
  void virtualFunc3(long x);
  void virtualFunc4(long x);
};

// Part 2

[Constructor(DOMString str, long i)]
interface StringUser {
  void Print(long anotherInteger, DOMString anotherString);
  void CallOther(StringUser fr);
};

